# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10bjx6K4mst6eF5z8dIgH7hw4-DzH1Aiu
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

# -----------------------------------
# Page Configuration
# -----------------------------------

st.set_page_config(
    page_title="Customer Segmentation using K-Means",
    page_icon="📊",
    layout="centered"
)

st.title("📊 Customer Segmentation using K-Means Clustering")

st.write("Name: Aamina Hasan")
st.write("Branch: CSE")
st.write("Room No: 612")

# -----------------------------------
# Load Dataset
# -----------------------------------

df = pd.read_csv("income.csv")

st.subheader("Dataset")

st.dataframe(df)

# -----------------------------------
# Original Scatter Plot
# -----------------------------------

st.subheader("Original Data")

fig, ax = plt.subplots()

ax.scatter(df["Age"], df["Income($)"])

ax.set_xlabel("Age")
ax.set_ylabel("Income ($)")

st.pyplot(fig)

# -----------------------------------
# Feature Scaling
# -----------------------------------

scaler = MinMaxScaler()

df["Age"] = scaler.fit_transform(df[["Age"]])

df["Income($)"] = scaler.fit_transform(df[["Income($)"]])

# -----------------------------------
# K-Means Model
# -----------------------------------

km = KMeans(n_clusters=3, random_state=42)

df["Cluster"] = km.fit_predict(df[["Age", "Income($)"]])

# -----------------------------------
# Clustered Dataset
# -----------------------------------

st.subheader("Clustered Dataset")

st.dataframe(df)

# -----------------------------------
# Cluster Plot
# -----------------------------------

st.subheader("K-Means Clustering")

fig, ax = plt.subplots()

colors = ["green", "red", "blue"]

for i in range(3):
    cluster = df[df["Cluster"] == i]
    ax.scatter(
        cluster["Age"],
        cluster["Income($)"],
        color=colors[i],
        label=f"Cluster {i}"
    )

ax.scatter(
    km.cluster_centers_[:,0],
    km.cluster_centers_[:,1],
    color="black",
    marker="*",
    s=200,
    label="Centroids"
)

ax.set_xlabel("Age")
ax.set_ylabel("Income ($)")
ax.legend()

st.pyplot(fig)

# -----------------------------------
# Elbow Method
# -----------------------------------

st.subheader("Elbow Method")

sse = []

k_range = range(1,10)

for k in k_range:
    model = KMeans(n_clusters=k, random_state=42)
    model.fit(df[["Age","Income($)"]])
    sse.append(model.inertia_)

fig, ax = plt.subplots()

ax.plot(k_range, sse, marker="o")

ax.set_xlabel("Number of Clusters (K)")
ax.set_ylabel("SSE")

st.pyplot(fig)